jenkins:
  systemMessage: "Jenkins engine provided for jobseeker etl framework.\n\nBy: Matheus Pavanetti"
  numExecutors: ${JENKINS_NUM_EXECUTORS}
  scmCheckoutRetryCount: 2
  mode: NORMAL
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: "${JENKINS_ADMIN_ID}"
         password: "${JENKINS_ADMIN_PASSWORD}"
  #mailer:
    #replyToAddress: do-not-reply@acme.org
    #smtpHost: smtp.acme.org
    #smtpPort: 4441