jenkins:
  systemMessage: "Jenkins engine provided for jobseeker etl framework.\n\nBy: Matheus Pavanetti"
  numExecutors: ${JENKINS_NUM_EXECUTORS}
  slaveAgentPort: ${JENKINS_AGENT_PORT}
  scmCheckoutRetryCount: 2
  mode: NORMAL
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: "${JENKINS_ADMIN_ID}"
         password: "${JENKINS_ADMIN_PASSWORD}"
unclassified:
  location:
    adminAddress: "${JOBSEEKER_SMTP_REPLY_TO}"
    url: "${JOBSEEKER_JENKINS_ROOT_URL}"
  mailer:
    replyToAddress: "${JOBSEEKER_SMTP_REPLY_TO}"
    smtpHost: "${JOBSEEKER_SMTP_HOST}"
    smtpPort: "${JOBSEEKER_SMTP_PORT}"
    useSsl: "${JOBSEEKER_SMTP_SSL}"
  email-ext:
    charset: "UTF-8"
    defaultContentType: "text/html"
    defaultReplyTo: "${JOBSEEKER_SMTP_REPLY_TO}"
    mailAccount:
      smtpHost: "${JOBSEEKER_SMTP_HOST}"
      smtpPort: "${JOBSEEKER_SMTP_PORT}"
      useSsl: "${JOBSEEKER_SMTP_SSL}"
      useTls: false
      useOAuth2: false
