server {
        listen 0.0.0.0:8080;
    root /var/www/html;
    index index.html index.php;
    client_max_body_size 100M;
        resolver 127.0.0.11 valid=30s ipv6=off;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header Referrer-Policy "same-origin" always;
        add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
        add_header Content-Security-Policy "frame-ancestors 'self'" always;

    # set expiration of assets to MAX for caching
    location ~* \.(ico|css|js|gif|jpe?g|png|json)(\?[0-9]+)?$ {
            expires max;
            log_not_found off;
    }

    location / {
            # Check if a file or directory index file exists, else route it to index.php.
            try_files $uri $uri/ /index.php;
    }

    location ^~ /adminer/ {
            return 404;
    }

    location ^~ /elfinder/ {
            return 404;
    }

    location ^~ /serverstatistics/ {
            return 404;
    }

    location ~* \.php$ {
            set $php_upstream php:9000;
            fastcgi_pass $php_upstream;
            include fastcgi.conf;
    }
}