#!/usr/bin/env python3
"""Moving inline jobs to Git, samples in Git workspaces, and build access, end to end.

A throwaway smart-HTTP Git server on the stack network stands in for GitHub
(the same one test-python-git-workspace-e2e.py uses). Also covers the stale
poetry.lock that `uv add` leaves behind, promotion of a job that is not Git
backed, configurable shell connectors in the dependency map, and SSH keys
that JobSeeker generates for a Profile Git account.
"""

from __future__ import annotations

import importlib.util
import json
import os
import shutil
import subprocess
import sys
import urllib.parse
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
os.environ.setdefault("JOBSEEKER_E2E_URL", "http://127.0.0.1:8088")
_spec = importlib.util.spec_from_file_location("sample_matrix", ROOT / "scripts" / "test-job-samples-e2e.py")
matrix = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(matrix)
_spec = importlib.util.spec_from_file_location("git_workspace", ROOT / "scripts" / "test-python-git-workspace-e2e.py")
git_workspace = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(git_workspace)

RUN = uuid.uuid4().hex[:6]
SERVER = f"jobseeker-git-move-{RUN}"
VOLUME = SERVER
NETWORK = os.environ.get("JOBSEEKER_E2E_NETWORK", "jobseeker_internal")
EMPTY_URL = f"http://{SERVER}:8000/empty.git"
SEEDED_URL = f"http://{SERVER}:8000/seeded.git"
BLANK_URL = f"http://{SERVER}:8000/blank.git"
MOVE_JOB = f"e2e-move-{RUN}"
CONFLICT_JOB = f"e2e-move-conflict-{RUN}"
SAMPLE_JOB = f"e2e-git-sample-{RUN}"
STALE_JOB = f"e2e-stale-lock-{RUN}"
CONNECTOR = f"e2e-git-build-{RUN}"
SSH_HOST = f"ssh-e2e-{RUN}.invalid"
SAMPLE_ID = "python-db-connector-inspect"

LEGACY_DOCKERFILE = "\n".join([
    "# Generated by JobSeeker inline Python; edit as needed.",
    "FROM python:3.13-slim",
    "ARG POETRY_VERSION=2.4.1",
    "WORKDIR /app",
    "ENV POETRY_VIRTUALENVS_CREATE=false \\",
    "    PIP_DISABLE_PIP_VERSION_CHECK=1 \\",
    "    PYTHONDONTWRITEBYTECODE=1 \\",
    "    PYTHONUNBUFFERED=1 \\",
    "    JOBSEEKER_DEPENDENCIES_PREINSTALLED=1",
    'RUN python -m pip install --no-cache-dir "poetry==$POETRY_VERSION" \\',
    "    && groupadd --system jobseeker \\",
    "    && useradd --system --gid jobseeker --create-home jobseeker",
    "COPY . .",
    "RUN if [ -s pyproject.toml ]; then poetry install --no-root --no-interaction --no-ansi; fi \\",
    "    && chown -R jobseeker:jobseeker /app",
    "USER jobseeker",
    "",
])

# What `uv add six` produces: a dependency poetry.lock has never seen.
STALE_PYPROJECT = """[project]
name = "jobseeker-stale-lock"
version = "0.1.0"
requires-python = ">=3.13,<4.0"
dependencies = [
    "six>=1.16",
]

[tool.poetry]
package-mode = false
"""
STALE_LOCK = """# This file is automatically @generated by Poetry 2.4.1 and should not be changed by hand.
package = []

[metadata]
lock-version = "2.1"
python-versions = ">=3.13,<4.0"
content-hash = "0000000000000000000000000000000000000000000000000000000000000000"
"""

passed = 0


def check(name: str, condition: bool, detail: str = "") -> None:
    global passed
    if not condition:
        print(f"FAIL: {name}" + (f"\n  {detail}" if detail else ""))
        sys.exit(1)
    passed += 1
    print(f"ok - {name}")


def run(*command: str, **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(command, capture_output=True, text=True, **kwargs)


def query(sql: str) -> str:
    return run("docker", "compose", "exec", "-T", "mariadb", "mariadb", "-umysql", "-pmysql",
               "-D", "jobseeker", "-N", "-e", sql, cwd=ROOT).stdout.strip()


def remote(*arguments: str) -> str:
    return run("docker", "exec", SERVER, "git", *arguments).stdout.strip()


def post_json(browser, path: str, fields: dict, expected=(200,)) -> tuple[int, dict]:
    status, body = browser.request(path, method="POST", csrf=True, fields=fields, expected=expected)
    try:
        return status, json.loads(body)
    except ValueError:
        check(f"{path} returned JSON", False, body[:800])
        raise


def inline_fields(job: str, code: str, **extra) -> dict:
    fields = {
        "job_name": job, "entry_point": "main.py", "pythonInlineCode": code,
        "pythonRequirementsText": "", "pythonPyprojectText": "", "pythonDockerfileText": "",
        "pythonInlineFilesJson": json.dumps({"files": [{"path": "helpers.py", "content": "VALUE = 1\n"}], "directories": []}),
        "pythonWorkspaceSignature": "", "pythonRuntimeMode": "docker", "pythonUseDockerfile": "1",
        "pythonVersion": "python3", "pythonDockerImage": "", "environment": "DEV", "pythonProjectId": "",
        "pythonRepositoryBranch": "", "commit_message": f"e2e move {RUN}", "overwrite": "0",
    }
    fields.update(extra)
    return fields


def main() -> None:
    browser = matrix.Browser()
    browser.request("/")
    _, page = browser.request("/loginMe", method="POST", csrf=True,
                              fields={"email": matrix.ADMIN_EMAIL, "password": matrix.ADMIN_PASSWORD})
    check("admin login", "logout" in page.lower())

    run("docker", "volume", "create", VOLUME)
    started = run("docker", "run", "-d", "--name", SERVER, "--network", NETWORK, "--user", "0", "-v", f"{VOLUME}:/srv",
                  "--entrypoint", "python3", "jobseeker-jenkins", "-c", git_workspace.GIT_HTTP_SERVER)
    account_ids: list[str] = []
    connector_id = ""
    jobs_saved: list[str] = []
    try:
        check("Git server started", started.returncode == 0, started.stderr)
        seeded = run("docker", "exec", SERVER, "sh", "-c",
                     "set -e; for name in empty seeded blank; do git init -q --bare -b main /srv/$name.git; done;"
                     " cd \"$(mktemp -d)\"; git init -q -b main; printf 'print(\"seeded\")\\n' > main.py; git add main.py;"
                     " git -c user.name=e2e -c user.email=e2e@example.com commit -qm seed; git push -q /srv/seeded.git main;"
                     " cd \"$(mktemp -d)\"; git init -q -b main; echo MIT > LICENSE; git add LICENSE;"
                     " git -c user.name=e2e -c user.email=e2e@example.com commit -qm license; git push -q /srv/blank.git main")
        check("remotes created (empty, seeded, blank)", seeded.returncode == 0, seeded.stderr)

        browser.request("/gitAccountSave", method="POST", csrf=True, fields={
            "provider": "generic", "label": "E2E move account", "host": SERVER + ":8000", "path_prefix": "",
            "auth_type": "token", "username": "e2e", "secret": "e2e-token", "known_hosts": "",
        })
        account_ids.append(query(f"SELECT id FROM user_git_accounts WHERE host='{SERVER}:8000' AND path_prefix='' LIMIT 1"))
        check("personal Git account saved", account_ids[-1].isdigit(), account_ids[-1])

        # --- Move an inline job into an empty repository -------------------
        inline_dir = ROOT / "repository" / "python" / "inline" / MOVE_JOB
        (inline_dir / ".venv").mkdir(parents=True)
        (inline_dir / ".venv" / "pyvenv.cfg").write_text("home = /usr\n")
        (inline_dir / "__pycache__").mkdir()
        (inline_dir / "__pycache__" / "main.cpython-313.pyc").write_bytes(b"\0")
        (inline_dir / ".env.jobseeker").write_text("JOBSEEKER_CONNECTOR_SESSION=secret\n")
        (inline_dir / "main.py").write_text('print("MOVE-OK")\n')
        status, moved = post_json(browser, "/jobCreation/inlinePythonConvertToGit",
                                  inline_fields(MOVE_JOB, 'print("MOVE-OK")\n', pythonRepositoryUrl=EMPTY_URL))
        check("Move to Git succeeds for an empty repository", moved.get("ok") is True, json.dumps(moved))
        check("an empty repository gets main before the DEV branch",
              moved.get("pushedBranches") == ["main", "develop"] and moved.get("branch") == "develop", json.dumps(moved))
        files = remote("--git-dir", "/srv/empty.git", "ls-tree", "-r", "--name-only", "develop").split("\n")
        for expected in ("main.py", "helpers.py", "pyproject.toml", "Dockerfile", ".gitignore", "tests/test_smoke.py"):
            check(f"{expected} was pushed", expected in files, "\n".join(files))
        check("no secrets, virtual environments, caches or editor files were pushed",
              not any(name.startswith((".venv", "__pycache__", ".vscode", ".continue")) or name == ".env.jobseeker" for name in files),
              "\n".join(files))
        check("main and develop point at the same commit",
              remote("--git-dir", "/srv/empty.git", "rev-parse", "main") == remote("--git-dir", "/srv/empty.git", "rev-parse", "develop"))
        check("the commit is authored as the JobSeeker user",
              remote("--git-dir", "/srv/empty.git", "log", "-1", "--format=%an|%s", "develop") == f"System Administrator|e2e move {RUN}",
              remote("--git-dir", "/srv/empty.git", "log", "-1", "--format=%an|%s", "develop"))
        workspace = ROOT / "repository" / "python" / "git" / MOVE_JOB
        git_status = run("git", "-C", str(workspace), "status", "--porcelain", "--branch").stdout
        check("the working copy is on develop, in sync and clean",
              git_status.strip().startswith("## develop...origin/develop") and len(git_status.strip().split("\n")) == 1, git_status)
        check("the working copy is ready for VS Code pushes",
              "jobseeker-git-credential" in run("git", "-C", str(workspace), "config", "--get-all", "credential.helper").stdout)
        status, again = post_json(browser, "/jobCreation/inlinePythonConvertToGit",
                                  inline_fields(MOVE_JOB, 'print("MOVE-OK")\n', pythonRepositoryUrl=EMPTY_URL), expected=(409,))
        check("moving the same job twice is refused", status == 409 and "already exists" in again.get("message", ""), json.dumps(again))

        # --- Move into a repository that already has different files -------
        status, conflict = post_json(browser, "/jobCreation/inlinePythonConvertToGit",
                                     inline_fields(CONFLICT_JOB, 'print("CONFLICT-OK")\n', pythonRepositoryUrl=SEEDED_URL), expected=(409,))
        check("conflicting files are reported, not overwritten",
              status == 409 and "main.py" in conflict.get("conflicts", []), json.dumps(conflict))
        check("a refused move leaves no working copy behind",
              not (ROOT / "repository" / "python" / "git" / CONFLICT_JOB).exists())
        status, replaced = post_json(browser, "/jobCreation/inlinePythonConvertToGit",
                                     inline_fields(CONFLICT_JOB, 'print("CONFLICT-OK")\n', pythonRepositoryUrl=SEEDED_URL, overwrite="1"))
        check("replacing existing files pushes only the job branch",
              replaced.get("ok") is True and replaced.get("pushedBranches") == ["develop"], json.dumps(replaced))
        check("the replaced file is on develop and main is untouched",
              'CONFLICT-OK' in remote("--git-dir", "/srv/seeded.git", "show", "develop:main.py")
              and remote("--git-dir", "/srv/seeded.git", "show", "main:main.py") == 'print("seeded")', "")

        # --- Samples go into a Git job's repository ------------------------
        sample_fields = {"job_name": SAMPLE_JOB, "environment": "DEV", "pythonRepositoryUrl": BLANK_URL,
                         "pythonRepositoryBranch": "", "pythonProjectId": "", "pythonEntryPoint": "", "sample_id": SAMPLE_ID}
        status, sample = post_json(browser, "/jobCreation/gitPythonLoadSample", sample_fields)
        sample_workspace = ROOT / "repository" / "python" / "git" / SAMPLE_JOB
        check("a sample is added to the repository root when nothing conflicts",
              sample.get("ok") is True and sample.get("sampleFolder") == "" and sample.get("entryPoint") == "main.py", json.dumps(sample)[:600])
        check("the sample brings its README and project file",
              (sample_workspace / "README.md").is_file() and (sample_workspace / "pyproject.toml").is_file()
              and (sample_workspace / "LICENSE").is_file(), str(sorted(p.name for p in sample_workspace.iterdir())))
        check("the sample opens in VS Code on develop",
              "openVsCodeUrl" in sample and run("git", "-C", str(sample_workspace), "rev-parse", "--abbrev-ref", "HEAD").stdout.strip() == "develop")
        status, second = post_json(browser, "/jobCreation/gitPythonLoadSample", sample_fields)
        check("a second copy goes into its own folder instead of overwriting",
              second.get("ok") is True and second.get("sampleFolder") == f"samples/{SAMPLE_ID}"
              and second.get("entryPoint") == f"samples/{SAMPLE_ID}/main.py"
              and (sample_workspace / "samples" / SAMPLE_ID / "README.md").is_file(), json.dumps(second)[:600])
        status, third = post_json(browser, "/jobCreation/gitPythonLoadSample", sample_fields, expected=(409,))
        check("adding the same sample again is refused", status == 409, json.dumps(third))

        # --- Build access ---------------------------------------------------
        base = {"job_name": CONFLICT_JOB, "environment": "DEV", "pythonRepositoryUrl": SEEDED_URL, "pythonProjectId": ""}
        status, public = post_json(browser, "/jobCreation/testGitBuildAccess",
                                   dict(base, pythonRepositoryBranch="main", pythonGitCredentialKey=""), expected=(422,))
        check("a private repository fails the public build check", public.get("ok") is False
              and "not publicly readable" in public.get("message", ""), json.dumps(public))
        browser.request("/dbSettings/InsertDbSettings?environment=DEV", method="POST", csrf=True, fields={
            "connector_key": CONNECTOR, "job_name": "*", "db_type": "git_repository", "auth_type": "token",
            "secret_backend": "local", "address": SERVER, "port": "8000", "schema": SEEDED_URL,
            "description": "Git build access e2e", "additional_parameters": "", "oracle_ServiceName": "",
            "oracle_sid": "", "login": "e2e", "password": "e2e-token", "local_secret_fields": "", "is_active": "1",
        })
        connector_id = query(f"SELECT id FROM database_settings WHERE connector_key='{CONNECTOR}' LIMIT 1")
        check("build connector saved", connector_id.isdigit(), connector_id)
        status, access = post_json(browser, "/jobCreation/testGitBuildAccess",
                                   dict(base, pythonRepositoryBranch="develop", pythonGitCredentialKey=CONNECTOR), expected=(200, 422))
        check("the build credential reads the job branch from a Jenkins worker", access.get("ok") is True, json.dumps(access))
        status, missing = post_json(browser, "/jobCreation/testGitBuildAccess",
                                    dict(base, pythonRepositoryBranch="no-such-branch", pythonGitCredentialKey=CONNECTOR), expected=(422,))
        check("a missing branch is reported as such", "does not exist" in missing.get("message", ""), json.dumps(missing))

        # --- A stale poetry.lock (after `uv add`) no longer breaks the build --
        browser.request("/jobCreation/send", method="POST", csrf=True, fields={
            "job_name": STALE_JOB, "job_names": "", "description": "Stale poetry.lock e2e", "environment": "DEV",
            "checkEnvironment": "1", "timestamp": "1", "trigger_after_save": "0", "linuxCommand": "1",
            "linuxExecutionStrategy": "python_inline", "linuxScriptType": "0", "pythonSourceMode": "upload",
            "pythonEntryPoint": "main.py", "pythonInlineCode": 'import six\nprint("STALE-LOCK-OK", six.__version__)\n',
            "pythonRequirementsText": "", "pythonPyprojectText": STALE_PYPROJECT, "pythonDockerfileText": LEGACY_DOCKERFILE,
            "pythonInlineFilesJson": json.dumps({"files": [], "directories": []}), "pythonWorkspaceSignature": "",
            "pythonRuntimeMode": "docker", "pythonUseDockerfile": "1", "pythonRunTests": "0", "pythonVersion": "python3",
            "pythonDockerImage": "python:3.13-slim", "containerCpuLimit": "1", "containerMemoryLimitMb": "1024",
            "checkBuild": "0", "abort": "0", "runJobCheck": "0", "emailCheck": "0", "editableEmailCheck": "0",
            "winCommand": "0", "action": "0"})
        jobs_saved.append(STALE_JOB)
        stale_dir = ROOT / "repository" / "python" / "inline" / STALE_JOB
        check("saving upgrades the legacy generated Dockerfile",
              "poetry check --lock" in (stale_dir / "Dockerfile").read_text(), (stale_dir / "Dockerfile").read_text())
        (stale_dir / "poetry.lock").write_text(STALE_LOCK)
        job = urllib.parse.quote(STALE_JOB, safe="")
        browser.request(matrix.proxy_path(f"job/{job}/buildWithParameters?ENVIRONMENT=DEV"), method="POST", csrf=True,
                        expected=(200, 201, 302))
        result, _, console = matrix.wait_for_build(browser, STALE_JOB)
        check("a job whose poetry.lock is stale builds and runs", result == "SUCCESS" and "STALE-LOCK-OK" in console, console[-2500:])
        check("the build explains the lock refresh", "poetry.lock does not match pyproject.toml" in console)

        status, preview = post_json(browser, "/Context/previewJobPromotion", {
            "sourceJob": STALE_JOB, "targetJobName": STALE_JOB + "-qa", "sourceEnvironment": "2", "targetEnvironment": "3",
            "targetGitBranch": "", "targetGitBranchMode": "default", "overwriteExisting": "0", "includeDependencies": "0",
            "promoteContexts": "0", "promotionProject": "", "overwriteContexts": "0", "createRollback": "0"})
        check("promoting a job that is not Git backed reports no branch",
              preview.get("ok") is True and preview.get("git_job_count") == 0 and preview.get("target_git_branch") is None,
              json.dumps(preview)[:800])

        # --- Dependency map: configurable shell connector -------------------
        status, scan = post_json(browser, "/jobCreation/scanDependencies", {
            "environment": "0", "job_name": "",
            "linuxCommandLine": 'connector_key="${JOBSEEKER_DB_CONNECTOR:-jobseeker-mariadb}"\njobseeker-connector test "$connector_key" --json\n'})
        check("a ${VAR:-default} shell connector is detected with no environment chosen",
              scan.get("environment") == "ALL" and [c.get("key") for c in scan.get("connectors", [])] == ["jobseeker-mariadb"],
              json.dumps(scan)[:800])

        # --- SSH key generated by JobSeeker ---------------------------------
        browser.request("/gitAccountSave", method="POST", csrf=True, fields={
            "provider": "generic", "label": "E2E generated key", "host": SSH_HOST, "path_prefix": "",
            "auth_type": "ssh_generate", "username": "", "secret": "",
            "known_hosts": SSH_HOST + " ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl"})
        account_ids.append(query(f"SELECT id FROM user_git_accounts WHERE host='{SSH_HOST}' LIMIT 1"))
        check("an SSH key account is created without pasting a key", account_ids[-1].isdigit(), account_ids[-1])
        _, profile = browser.request("/profile/git")
        public_key = query(f"SELECT public_key FROM user_git_accounts WHERE id={account_ids[-1]}")
        check("its public key is shown to add to the provider",
              public_key.startswith("ssh-ed25519 ") and public_key.split(" ")[1] in profile, public_key)
        status, body = browser.request("/gitKnownHosts?host=bad%20host", expected=(400,))
        check("host-key lookup rejects an invalid host", status == 400)
    finally:
        for job_name in jobs_saved:
            browser.request("/delete-job/jobs", method="POST", csrf=True, fields={"jobs": job_name, "environment": "DEV"})
        if connector_id:
            browser.request("/dbSettings/deleteSetting?environment=DEV", method="POST", csrf=True, fields={"userId": connector_id})
        for account_id in account_ids:
            if account_id.isdigit():
                browser.request("/gitAccountDelete", method="POST", csrf=True, fields={"id": account_id})
        for kind, job_name in (("git", MOVE_JOB), ("git", CONFLICT_JOB), ("git", SAMPLE_JOB),
                               ("inline", MOVE_JOB), ("inline", CONFLICT_JOB), ("inline", STALE_JOB)):
            shutil.rmtree(ROOT / "repository" / "python" / kind / job_name, ignore_errors=True)
        run("docker", "rm", "-f", SERVER)
        run("docker", "volume", "rm", VOLUME)

    print(f"\nGit move/sample e2e: {passed} checks passed.")


if __name__ == "__main__":
    main()
