apiVersion: v1
kind: ConfigMap
metadata:
  name: jobseeker-config
data:
  JOBSEEKER_DEPLOYMENT_MODE: standalone
  JOBSEEKER_STANDALONE_ENVIRONMENT: DEV
  JOBSEEKER_JENKINS_ENVIRONMENT_SLOTS: DEV=5
  JOBSEEKER_JENKINS_ENVIRONMENT_AGENT_LABELS: DEV=jobseeker-env-standalone
  JOBSEEKER_KUBERNETES_CONTAINER_CAP: "5"
  JOBSEEKER_KUBERNETES_STANDALONE_AGENT_CAP: "5"
